accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.sign_up, name='signup'),

    path(
        'login/',
        auth_views.LoginView.as_view(
            template_name='accounts/login.html'
        ),
        name='login'
    ),

    path('logout/', views.logout_view, name='logout'),

    
]

config/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    
    # usa o include para delegar parte das URLs para outro arquivo 
    path('', include('core.urls')), # URLs que começam com /core/
    path('accounts/', include('accounts.urls')), # URLs que começam com /accounts/
    path('appointments/', include('appointments.urls')), # URLs que começam com /appointments/
    
    path(
        'accounts/password-reset/',
        auth_views.PasswordResetView.as_view(
            template_name='accounts/password_reset.html',
            success_url=reverse_lazy('password_reset_done')
        ),
        name='password_reset'
    ),

    path(
        'accounts/password-reset/done/',
        auth_views.PasswordResetDoneView.as_view(
            template_name='accounts/password_reset_done.html'
        ),
        name='password_reset_done'
    ),

    path(
        'accounts/reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='accounts/password_reset_confirm.html',
            success_url=reverse_lazy('password_reset_complete')
        ),
        name='password_reset_confirm'
    ),

    path(
        'accounts/reset/done/',
        auth_views.PasswordResetCompleteView.as_view(
            template_name='accounts/password_reset_complete.html'
        ),
        name='password_reset_complete'
    ),
]

core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.home, name='home'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import RegexValidator


exactly_11_digits_validator = RegexValidator(
    regex=r'^\d{11}$',
    message='Este campo deve conter exatamente 11 números.'
)

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    
    
    celular = models.CharField(
        max_length=11,
        validators=[exactly_11_digits_validator],
    )

    cpf = models.CharField(
        max_length=11,
        unique=True,
        validators=[exactly_11_digits_validator],
    )

    data_nascimento = models.DateField()

    is_terapeuta = models.BooleanField(default=False)

    sexo = models.CharField(max_length=1, choices=[
        ('M', 'Masculino'),
        ('F', 'Feminino'),
        ('O', 'Outro'),
    ])
    
    def __str__(self):
        return self.user.username
    #enddef
#endclass

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile

class SignupForm(UserCreationForm):
    email = forms.EmailField(required=True)
    
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
    #endclass
    
    def save(self, commit=True):
        user = super().save(commit=False)
        
        user.email = self.cleaned_data['email']
        
        if commit:
            user.save()
        #endif
        
        return user
    #enddef
#endclass

class ProfileForm(forms.ModelForm):
    is_terapeuta = forms.BooleanField(required=False, label="Sou terapeuta")
    
    class Meta:
        model = Profile
        
        fields = ('cpf', 'sexo', 'data_nascimento', 'celular', 'is_terapeuta')
        
        widgets = {'data_nascimento': forms.DateInput(attrs={'type': 'date'})}
    #endclass
#endclass

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db import transaction
from .forms import ProfileForm, SignupForm

def sign_up(request):
    if request.method == 'POST':
        user_form = SignupForm(request.POST)
        profile_form = ProfileForm(request.POST)
        
        if user_form.is_valid() and profile_form.is_valid():
            with transaction.atomic():
                user = user_form.save()
                
                profile = profile_form.save(commit=False)
                profile.user = user
                profile.save()
                
                if profile.is_terapeuta:
                    user.is_staff = True
                    user.save(update_fields=['is_staff'])
                #endif
                
                messages.success(request, 'Conta criada com sucesso!')
                
                login(request, user)
                
                return redirect('core:home')
            #endwith
        #endif
    #endif
    else:
        user_form = SignupForm()
        profile_form = ProfileForm()
    #endelse
    
    return render(request, 'accounts/signup.html', {'user_form': user_form, 'profile_form': profile_form,})
#enddef

@login_required
def logout_view(request):
    logout(request)
    
    messages.success(request, 'Você saiu da sua conta com sucesso!')
    
    return redirect('core:home')    
#enddef

accounts/templates/accounts/login.html
{% extends "base.html" %}
{% load static %}

{% block title %}Login{% endblock %}

{% block extra_css %}<link rel="stylesheet" href="{% static 'css/login.css' %}">{% endblock %}

{% block content %}
    <div class="login-container">
        <div class="login-card">
            <h1 class="font-title login-title">Login</h1>   
            <form method="post" class="login-form">
                {% csrf_token %}

                {{form.non_field_errors}}

                <div class="form-group">
                    <label for="id_username" class="font-text">Usuário</label>

                    {{form.username}}
                </div>

                <br>

                <div class="form-group">
                    <label for="id_password" class="font-text">Senha</label>

                    {{form.password}}

                    <p class="font-text" style="text-align: end;">Esqueceu sua senha? <a class="forgot-password" href="{% url "password_reset" %}">Clique aqui</a></p>
                </div>

                <br>
                
                <button type="submit" class="btn-login">Entrar</button>
            </form>
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/password_reset.html
{% extends "base.html" %}

{% load static %}

{% block extra_css %}<link rel="stylesheet" href="{% static 'css/password.css' %}">{% endblock %}

{% block content %}
<div class="password-container">
    <div class="password-card">
        <h1 class="font-title password-title">Recuperar senha</h1>   
        <form method="post" class="password-form">
            {% csrf_token %}

            {{form.non_field_errors}}

            <div class="form-group">
                <label for="id_email" class="font-text">Email</label>

                {{form.email}}
            </div>

            <br>
            
            <button type="submit" class="btn-password">Enviar email</button>
        </form>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/password_reset_complete.html
{% extends "base.html" %}

{% load static %}

{% block extra_css %}<link rel="stylesheet" href="{% static 'css/password.css' %}">{% endblock %}

{% block content %}
<div class="password-container">
    <div class="password-card">
        <h1 class="font-title password-title">Redefinir senha</h1>

        <p class="font-text">Senha redifinida com sucesso!</p>

        <br>
        
        <a href="{% url "accounts:login" %}" class="font-text btn-password-complete" id="do-login-password-recovery">Fazer login</a>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/password_reset_confirm.html
{% extends "base.html" %}

{% load static %}

{% block extra_css %}<link rel="stylesheet" href="{% static 'css/password.css' %}">{% endblock %}

{% block content %}
<div class="password-container">
    <div class="password-card">
        <h1 class="font-title password-title">Redefinir senha</h1>   
        <form method="post" class="password-form">
            {% csrf_token %}

            <div class="form-group">
                {{form.as_p}}
            </div>

            <br>
            
            <button type="submit" class="btn-password">Salvar nova senha</button>
        </form>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/password_reset_done.html
{% extends "base.html" %}

{% load static %}

{% block extra_css %}<link rel="stylesheet" href="{% static 'css/password.css' %}">{% endblock %}

{% block content %}
<div class="password-container">
    <div class="password-card">
        <h1 class="font-title password-title">Recuperar senha</h1>   
        <p class="font-text">Se existir uma conta com esse email, você receberá instruções para redefinir sua senha.</p>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends "base.html" %}
{% load static %}

{% block title %}Cadastro{% endblock %}

{% block extra_css %}<link rel="stylesheet" href="{% static 'css/signup.css' %}">{% endblock %}

{% block content %}
    <div class="signup-container">
        <div class="signup-card">
            <h1 class="font-title signup-title">Criar conta</h1>

            <form method="post" class="signup-form">
                {% csrf_token %}

                {{ user_form.non_field_errors }}

                <div class="fieldset-container">
                    <fieldset>
                        <legend>Dados de acesso</legend>
    
                        {% for field in user_form %}
                            <div class="form-group">
                                <label for="{{field.id_for_label}}" class="font-text">{{ field.label }}</label>
                                {{ field }}
    
                                {% if field.errors %}
                                    <small class="error">{{ field.errors|striptags }}</small>
                                {% endif %}
                            </div>
                        {% endfor %}
                    </fieldset>
    
                    <fieldset>
                        <legend>Dados pessoais</legend>
    
                        {% for field in profile_form %}
                            <div class="form-group">
                                {% if field.field.widget.input_type == "checkbox" %}
                                    <label class="checkbox-label">
                                        {{ field }}
                                        <span class="font-text">{{ field.label }}</span>
                                    </label>
                                {% else %}
                                    <label for="{{field.id_for_label}}" class="font-text">{{ field.label }}</label>
                                    {{ field }}
                                {% endif %}
                                
                                {% if field.errors %}
                                    <small class="error">{{ field.errors|striptags }}</small>
                                {% endif %}
                            </div>
                        {% endfor %}
                    </fieldset>
                </div>
                
                <button type="submit" class="btn-signup">Cadastrar</button>
            </form>

            <p class="signup-footer">
                Já possui uma conta?
                <a href="{% url 'accounts:login' %}">Entrar</a>
            </p>
        </div>
    </div>
{% endblock %}