accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.sign_up, name='signup'),

    path(
        'login/',
        auth_views.LoginView.as_view(
            template_name='accounts/login.html'
        ),
        name='login'
    ),

    path('logout/', views.logout_view, name='logout'),

    
]

appointments/urls.py
from django.urls import path
from . import views

app_name = 'appointments'

urlpatterns = [
    path('new/', views.create_appointment, name='create'),
    path('my/', views.my_appointments, name='my_appointments'),
    path('all/', views.all_appointments, name='all_appointments'),
    path('services/', views.make_services, name='make_services'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    
    # usa o include para delegar parte das URLs para outro arquivo 
    path('', include('core.urls')), # URLs que começam com /core/
    path('accounts/', include('accounts.urls')), # URLs que começam com /accounts/
    path('appointments/', include('appointments.urls')), # URLs que começam com /appointments/
    
    path(
        'accounts/password-reset/',
        auth_views.PasswordResetView.as_view(
            template_name='accounts/password_reset.html',
            success_url=reverse_lazy('password_reset_done')
        ),
        name='password_reset'
    ),

    path(
        'accounts/password-reset/done/',
        auth_views.PasswordResetDoneView.as_view(
            template_name='accounts/password_reset_done.html'
        ),
        name='password_reset_done'
    ),

    path(
        'accounts/reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='accounts/password_reset_confirm.html',
            success_url=reverse_lazy('password_reset_complete')
        ),
        name='password_reset_confirm'
    ),

    path(
        'accounts/reset/done/',
        auth_views.PasswordResetCompleteView.as_view(
            template_name='accounts/password_reset_complete.html'
        ),
        name='password_reset_complete'
    ),
]

core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.home, name='home'),
]

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'core/home.html')
#enddef

core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Massoterapia{% endblock  %}</title>

    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="icon" href="{% static 'img/favicon.png' %}">

    {% block extra_css %}{% endblock %}
</head>
<body>
    <header>
        <div class="logo">
            <img src="{% static "img/logo.png" %}" alt="Logo">
        </div>
        <nav class="navbar">
            <div class="landing-page-nav">
                <a class="font-nav" href="/#hero">Início</a>
                <a class="font-nav" href="/#about">Sobre mim</a>
                <a class="font-nav" href="/#therapies">Terapias</a>
            </div>
            <div class="utils-nav">
                {% if user.is_authenticated %}
                    <a class="font-nav" href="{% url "appointments:create" %}">Agendar</a>
                    
                    {% if user.is_staff %}
                        <a class="font-nav" href="{% url "appointments:all_appointments" %}">Todos agendamentos</a>
                        <a class="font-nav" href="{% url "appointments:make_services" %}">Cadastrar serviços</a>
                    {% else %}
                        <a class="font-nav" href="{% url "appointments:my_appointments" %}">Meus agendamentos</a>
                    {% endif %}

                    <form method="post" action="{% url 'accounts:logout' %}" style="display: inline;">
                        {% csrf_token %}
                        
                        <button class="button" type="submit">Sair</button>
                    </form>
                {% else %}
                    <a class="button" href="{% url "accounts:login" %}">Login</a>
                    <a class="button" href="{% url "accounts:signup" %}">Cadastrar</a>
                {% endif %}
            </div>
        </nav>
    </header>

    <main>
        {% block content %}{% endblock %}
    </main>

    <footer >
        <div>
            <p class="font-title">Milena Madeira | Massoterapeuta </p>
       
        </div>
        <div>
            <p class="font-text">Atendimento em Belo Horizonte e Sabará | Whatsapp: (31)9xxxx-xxxx</p>
            <p class="font-text">© 2026 — Todos os direitos reservados</p>
        </div>
    </footer>

    <script src={% static 'js/scripts.js' %}></script>

    {% block extra_js %}{% endblock %}

    {% if messages %}
    <div class="messages-container">
        {% for message in messages %}
            <div class="django-message {{ message.tags }}">
                {{ message }}
            </div>
        {% endfor %}
    </div>
{% endif %}

</body> 
</html>

core/templates/core/home.html
{% extends "base.html" %}
{% load static %}

{% block title %}Início{% endblock %}

{% block extra_css %}<link rel="stylesheet" href="{% static 'css/home.css' %}">{% endblock %}

{% block content %}
    <section class="hero" id="hero">       
        <div class="hero-text">
            <h1 class="font-title">
                Terapias naturais para equilíbrio, bem-estar e qualidade de vida
            </h1>

            <p class="font-text">
                Atendimento humanizado com foco em saúde emocional, corporal e energética,
                promovendo mais qualidade de vida e autocuidado.
            </p>

            <div class="hero-actions">
                <a href="#about" class="button">Sobre mim</a>
                <a href="#therapies" class="button">Conheça as terapias</a>
            </div>
        </div>

        <div class="hero-image"></div>
    </section>

    <section class="about" id="about">
        <h1 class="font-title">Sobre mim</h1>
        <div class="about-container">
            <img src="{% static 'img/milena.jfif' %}">
            <p class="font-text">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam molestie cursus erat in tincidunt. Aliquam ex leo, ultricies mollis arcu non, vehicula mollis sapien. Phasellus sollicitudin hendrerit scelerisque. Donec nec feugiat turpis. Duis facilisis nisl eu dui sodales pretium. Pellentesque suscipit sit amet arcu a auctor. Morbi aliquam viverra sapien, sed ullamcorper magna scelerisque vitae. Sed lobortis enim a ante vulputate, quis accumsan ex tristique. Donec tempor est a orci commodo, quis eleifend ante laoreet. Vestibulum eget dolor orci. Phasellus tempus a nibh et imperdiet. Maecenas dictum quam dolor, id sodales diam facilisis quis. Nam sit amet turpis in ex aliquam molestie. Cras accumsan, sapien nec pretium euismod, diam libero auctor risus, id mattis risus mauris sed libero. Ut porta, velit non luctus porta, nunc erat consectetur arcu, at accumsan mauris erat at sem. Duis aliquet mauris sed felis euismod, in egestas justo dictum.<br>
                Sed efficitur malesuada elit, nec varius erat ultricies vitae. Vestibulum malesuada at urna rhoncus fringilla. Nunc a dui accumsan, iaculis nibh nec, ornare libero. Praesent in scelerisque leo, vel fermentum elit. Sed ut diam luctus, elementum nisi tempor, commodo leo. Integer viverra enim et nunc pretium mattis. Vivamus eu tellus at nisi dictum tincidunt. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Integer consectetur molestie tortor, sed ultrices metus laoreet nec.
            </p>
        </div>
    </section>

    <section class="therapies" id="therapies">
        <h1 class="font-title" style="text-align:center">Terapias</h1>
        <div class="therapies_container">
            <div class="therapy">
                <img src="{% static 'img/finger_yoga.jpg' %}">
                <h1 class="font-title">Finger Yoga</h1>
                <p class="font-text" style="padding:0 1.5rem">Finger yoga é uma técnica bem-estar baseada em gestos feitos com os dedos, 
                    conhecidos como <strong>mudras</strong>. Esses movimentos estimulam terminações nervosas e pontos energéticos das mãos, 
                    ajudando a promover <strong>relaxamento, equilíbrio emocional, melhora da concentração e alívio do estresse</strong>. 
                    Pode ser praticada em qualquer lugar, sem necessidade de equipamentos, sendo uma ótima opção para quem busca momentos 
                    rápidos de autocuidado e conexão entre corpo e mente.</p>
            </div> 

            <div class="therapy">
                <img src="{% static 'img/reflexologia_podal.jpg' %}">
                <h1 class="font-title">Reflexologia Podal</h1>
                <p class="font-text" style="padding:0 1.5rem">Reflexologia podal é uma técnica terapêutica que consiste na aplicação
                    de pressão em pontos específicos dos <strong>pés</strong>, chamados de zonas reflexas, que correspondem a diferentes
                    órgãos e partes do corpo. O estímulo desses pontos ajuda a melhorar a <strong>circulação, aliviar tensões, reduzir o estresse
                    e promover o equilíbrio do organismo</strong>. Além de proporcionar relaxamento, a reflexologia é utilizada como prática 
                    complementar para o bem-estar físico e emocional.</p>
            </div> 

            <div class="therapy">
                <img src="{% static 'img/shiatsu.jpg' %}">
                <h1 class="font-title">Shiatsu</h1>
                <p class="font-text" style="padding:0 1.5rem">Shiatsu é uma técnica terapêutica de origem japonesa que utiliza a <strong>pressão dos dedos, 
                    palmas das mãos e, em alguns casos, cotovelos</strong>, sobre pontos específicos do corpo. Essa prática estimula a circulação de energia, 
                    alivia tensões musculares, reduz o estresse e contribui para o <strong>equilíbrio físico e emocional</strong>. O shiatsu também auxilia na melhora da postura, 
                    da circulação sanguínea e na promoção do relaxamento e bem-estar geral.</p>
            </div>

            <div class="therapy">
                <img src="{% static 'img/auriculoterapia.png' %}">
                <h1 class="font-title">Auriculoterapia</h1>
                <p class="font-text" style="padding:0 1.5rem">Auriculoterapia é uma técnica terapêutica baseada na estimulação de <strong>pontos específicos da orelha</strong>, 
                    que representam diferentes órgãos e funções do corpo. Esses pontos podem ser ativados por meio de pressão, sementes, esferas ou agulhas, 
                    auxiliando no <strong>alívio de dores, redução do estresse, controle da ansiedade e melhora do equilíbrio físico e emocional</strong>. 
                    É uma prática complementar amplamente utilizada para promover o bem-estar e apoiar diversos tratamentos de saúde.</p>
            </div>
        </div>
    </section>
{% endblock  %}